name: Build check
on: 
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "*.md"
    types:
      - opened
      - synchronize
      - reopened
  push:
    paths-ignore:
      - "*.md"
    branches:
      - main
      - mh3u-revival
      - game-mode

permissions:
  contents: read
  packages: write # vcpkg caches built libraries in this repo's GitHub Packages

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
